## Exercise 6 - Numpy

1 Generate two NumPy arrays so that first array has integers from 10 to 40 (inclusive). Second array should have integers from 220 to 250 (inclusive). Sum these arrays and present the result array.

In [1]:
import numpy as np
arr1 = np.arange(start=10, stop=41, step=1)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [2]:
arr2 = np.arange(start=220, stop=251, step=1)
arr2

array([220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232,
       233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245,
       246, 247, 248, 249, 250])

In [3]:
arr3 = arr1 + arr2
arr3

array([230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254,
       256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280,
       282, 284, 286, 288, 290])

2 Generate two-dimensional array with 10 rows and 7 columns containing integers starting from 100.

In [9]:
a4 = np.arange(start=100, stop=170).reshape(10,7)
a4

array([[100, 101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127],
       [128, 129, 130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139, 140, 141],
       [142, 143, 144, 145, 146, 147, 148],
       [149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162],
       [163, 164, 165, 166, 167, 168, 169]])

3 Generate two one-dimensional arrays having integers between 1-50. First array should have even and second array should have odd numbers. Finally multiply each element from corresponding index positions from these two arrays for the result array. For example [(1 x 2),(3 x 4),(5 x 6),(7 x 8)...].

In [12]:
odd = np.arange(start=1,stop=51, step=2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [14]:
even = np.arange(start=2,stop=51, step=2)
even


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [15]:
result = np.multiply(odd, even)
result

array([   2,   12,   30,   56,   90,  132,  182,  240,  306,  380,  462,
        552,  650,  756,  870,  992, 1122, 1260, 1406, 1560, 1722, 1892,
       2070, 2256, 2450])

4 Generate two-dimensional array (40 rows, 5 columns) containing random integers between 1 and 1000. Filter the result array so that only numbers divisable with numbers 2 and 5 are presented (number must be divisable with both).

In [24]:
randoms = np.random.randint(1,1001, 200).reshape(40,5)
randoms

array([[ 268,  946,  547,  925,  837],
       [ 757,   69,  259,   42,  231],
       [ 670,  784,  594,  843,  609],
       [ 379,  736, 1000,  654,  260],
       [ 479,  604,  336,   59,   74],
       [ 451,  752,  719,  131,  450],
       [ 856,  786,  744,  958,    8],
       [ 858,  495,  978,  157,  483],
       [ 273,  281,   45,  726,   26],
       [ 753,  821,  120,  515,  409],
       [ 965,   58,  419,  456,  813],
       [ 210,   58,  715,  588,  316],
       [ 921,  190,  364,  566,  576],
       [ 188,  843,  819,  392,  361],
       [  39,  544,   96,  383,  663],
       [ 329,  841,  999,   60,  449],
       [ 598,  330,  484,  134,  758],
       [ 395,  244,  273,  659,  450],
       [ 179,   32,  435,  446,  528],
       [ 343,  238,  739,  659,  727],
       [ 286,  264,  532,  559,  128],
       [ 930,  564,  297,  962,  222],
       [  19,  920,  319,  960,  257],
       [ 255,  790,  513,  420,    3],
       [ 430,  369,  407,  563,  427],
       [ 220,  292,  322,

In [37]:
mask = (randoms % 2 == 0) & (randoms % 5 == 0)
divisableby2and5 = randoms[mask]
divisableby2and5

array([ 670, 1000,  260,  450,  120,  210,  190,   60,  330,  450,  930,
        920,  960,  790,  420,  430,  220,  160,  510,  390,  650])